### ISSUE TITLE
run in background

### ISSUE THREAD

**Issue by datahub-projects** [burstable-ai/burst#18]
* loong-running training sessions may fail if ssh connection dies
* screen? or something similar (tmux etc)
* run docker as daemon? (without -`ti`)
#feat @dan #leela

**Comment by datahub-projects** [comment]
Suggested user experience:

* if `--background` flag is true, after build & rsync, `burst` returns and further processing goes on in background.
* `--status` flag reports status of tasks (including shutdown which is already a background task)
* `--terminal` flag opens a terminal shell and logs into running process
  + note this can also be a non-background task
* `--timeout` specifies how long a process is idle before it is killed
  + this is for the jupyterlab or http scenario
  + notice this is different than shutdown, which only applies when the process completes

**Comment by kevinscollins** [comment]
### Some Use Cases

* Legit long-running job that shouldn't be shut down when the connection is lost
1. How does the user see jobs that have finished while they were disconnected?
2. How does the user reconnect to a finished job and pull the files? Is there a check on the folder?
* Broken long-running job that should be shut down but is still burning the GPU/CPU when the connection is lost
* Long-running job that isn't doing anything but doesn't exit (eg, interactive bash) when the connection is lost

**Comment by kevinscollins** [comment]
WRT, what about `--tasks` instead of `--status`? Or maybe we just add this info to `--list-servers` since we don't support more than one task per VM?

**Comment by danx0r** [comment]
Thoughts about MVF for this issue (Minimum Viable Fix)

launch shutdown container before user args are run (during build//rsync setup phase)
* this container should be launched once when VM is started
  + integrate with rclone container?
* communicate with shutdown container with `~/.burst-shutdown`
  + if it exists, contains a date/time to shut down
  + first thing we always do is delete `~/.burst-shutdown` (where now we search & destroy shutdown container)
  + for normal (non-background) operation, shutdown timer starts after rsync (same place as now but instead of launching the shutdown container we just create `~/.burst-shutdown`
  + if `--background`, add creation of `~/.burst-shutdown` to user args
* add `--synchronize`
* add `--tasks` (instead of `--status`)

NOT in MVF: logging in or screen-like reattach
